version: "3"
services:
  db:
    container_name: psql
    restart: always
    image: psql
    build:
      context: ./packages/database
    volumes:
      - ./packages/database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: photo_sans
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - psql-pgql

  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DB_POSTGRES_URL}"
    expose:
      - 5000
    ports:
      - 5000:5000
    command:
      [
        "postgraphile",
        "--connection",
        "${DB_POSTGRES_URL}",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--schema",
        "photography",
      ]
    links:
      - db
    networks:
      - psql-pgql

networks:
  psql-pgql:
